name: "book"

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to main
on:
  push:
    branches:
      - main

jobs:
  marimo:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - uses: jebel-quant/marimushka@v0.1.4
        with:
          notebooks: 'book/marimo'

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/pdoc@v2.2.8
        with:
          source-folder: 'src/cvx'

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/coverage@v2.2.8
        with:
          source-folder: 'src/cvx'
          tests-folder: 'src/tests'

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/jupyter@v2.2.8

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter, marimo]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.2.8
